# .gitlab-ci.yml

# Specify the image to use for the job
image: node:18.17.1

# Define the stages of the pipeline
stages:
  - test

# Job to run tests
test:
  stage: test
  before_script:
    # Install dependencies
    - npm install
    # Install Cypress globally
    - npm install -g cypress

  script:
    # Run unit tests with Vitest
    - npm run test:unit
    # Run cypress tests
    - cypress run

