# .gitlab-ci.yml

# Specify the image to use for the job
image: node:18.17.1

variables:
  # Définition des variables pour éviter la répétition
  APT_PACKAGES: "libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb"

cache:
  paths:
    - node_modules/

# Define the stages of the pipeline
stages:
  - deploy
  - test
  - install
  - sonarqube-check
  - cypress
  - eslint

services:
  - docker:dind

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - echo "Logging in to GitLab Docker registry..."
    - echo "$CI_REGISTRY_PASSWORD_GLOBAL" | docker login -u "$CI_REGISTRY_USER_GLOBAL" --password-stdin $CI_REGISTRY_GLOBAL
  script:
    - docker run -d -p 3000:3000 registry.gitlab.com/bubbleproject/bubbleback:main
  only:
    - main
    - develop


# Job to run tests
test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test:unit

cypress: 
  stage: cypress
  before_script:
    - apt-get update && apt-get install -y $APT_PACKAGES
    - npm install -g cypress
    - npm ci --cache .npm --prefer-offline
  script: 
    - npm run dev&
    - npx cypress run

eslint: 
  stage: eslint
  before_script:
    - npm ci --cache .npm --prefer-offline
  script: 
    - npm run lint 

sonarqube-check:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true