# .gitlab-ci.yml

# Specify the image to use for the job
image: node:18.17.1

variables:
  # Définition des variables pour éviter la répétition
  APT_PACKAGES: "libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb"

cache:
  paths:
    - node_modules/

before_script:
  - npm ci --cache .npm --prefer-offline

# Define the stages of the pipeline
stages:
  - deploy
  - test
  - cypress
  - eslint

deploy:
  stage: deploy
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - echo "Logging in to GitLab Docker registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull registry.gitlab.com/bubbleproject/bubbleback:latest
    - docker-compose up -d


# Job to run tests
test:
  stage: test
  script:
    - npm run test:unit

cypress: 
  stage: cypress
  before_script:
    - apt-get update && apt-get install -y $APT_PACKAGES
    - npm install -g cypress
  script: 
    - npm run dev&
    - npx cypress run

eslint: 
  stage: eslint
  script: 
    - npm run lint 
